### ISSUE TITLE
Userstory 1

### ISSUE THREAD

**Issue by DenisKorkmaz** [DenisKorkmaz/Capstone-Project-News-App#1]
name: View Articles
about: Viewing articles with image and title
labels: enhancement

---

## Value Proposition

**As a User I want to see articles with images and titles and be able to see the full web version of the article.

## Description

![Image](https://github.com/DenisKorkmaz/Capstone-Project-News-App/assets/127840761/a908ec8e-f99d-4e3a-90bb-7116de4c9ed1)

A main screen with a list of articles, including a thumbnail image and the title for each article.

## Acceptance Criteria

- [x] All current articles must be displayed with images and titles.
- [x] Clicking on an article redirects the user to the full web version of the article.

## Tasks

- [x] Create the main component for displaying articles.
- [x] Implement connection to Tagesschau API to fetch articles.
- [x] Create individual article components with image and title.
- [x] Implement routing to redirect users to full web version of articles.
- [x] Implement styles using styled-components

## Complexity

M
