### ISSUE TITLE
User Story 2

### ISSUE THREAD

**Issue by DenisKorkmaz** [DenisKorkmaz/Capstone-Project-News-App#2]
### Value Proposition
As a User I want to search for news articles. So that I can find specific information I am interested in.

### Description
The home page should have a search bar that allows users to search for news articles.

### Acceptance Criteria
- [ ] Users can type in the search bar and hit enter to initiate a search.

### Tasks
- [ ] Implement a search bar on the home page.
- [ ] Connect the search bar to the API's search function.

### Complexity
M
