### ISSUE TITLE
User Story 3

### ISSUE THREAD

**Issue by DenisKorkmaz** [DenisKorkmaz/Capstone-Project-News-App#3]
### Value Proposition
As a User I want to filter news articles by categories. So that I can focus on news that interests me most.

### Description
The home page should have filter options that allow users to filter news articles by categories.

### Acceptance Criteria
- [ ] Users can select categories to filter the news articles.

### Tasks
- [ ] Implement filter options on the home page.
- [ ] Connect the filter options to the API's category filter function.

### Complexity
M
