### ISSUE TITLE
Userstory 4: Search for Specific Articles on Home and Favorites Page

### ISSUE THREAD

**Issue by DenisKorkmaz** [DenisKorkmaz/Capstone-Project-News-App#7]
### Search for Specific Articles on Home and Favorites Page

**Value Proposition**  
As a User, I want to search for specific articles on the home and favorites page so that I can quickly find articles based on my specific interests.

**Description**  

![Bildschirmfoto 2023-08-14 um 10 52 04](https://github.com/DenisKorkmaz/Capstone-Project-News-App/assets/127840761/7ed22921-42c5-4615-b33a-a9896de97bf0)

A search bar will be placed prominently on both the home and favorites pages. When users input a search term, the page will display articles that match the search term.

**Acceptance Criteria**  
- [x] Search bar is present on both the home and favorites page.
- [x] Users can search for articles using the search bar.
- [x] Articles displayed match the search term.
- [x] If no articles match the search term, an appropriate message is shown.

**Tasks**  
1. Implement the search bar on the home and favorites page.
2. Fetch and display articles based on the search term.
3. Design and implement the feedback message for no articles found.
4. Implement styles using styled-components.

**Complexity**  
M

---

**Comment by CJAkkuec** [comment]
> As a User, I want to filter articles by region and category, **and** also have the ability to search for specific articles on the home and favorites page so that I can quickly find articles relevant to my interests.
The "and" in bold is where this user story adds another feature to the one described in the first half of the sentence.

One feature would be the ability to filter articles, the other feature would be implementing a search function.

I'd suggest slicing this user story into two. The upside: you've already got another user story.

_(Sidenote: You're mixing languages in your wireframe, which isn't ideal.)_

**Comment by AntjeWitte** [comment]
Looks good to me!

**Comment by CJAkkuec** [comment]
> As a User, I want to search for specific articles on the home and favorites page so that I can quickly find articles based on my specific interests.

I feel like the implication would be that the search is happening anywhere. There should be an overlap between what's displayed on the home page and what is displayed on the favorites page, so I don't think you need to look in two places, you just need to look at the single source of truth that provides either page with its content.
